# Generated by Django 4.2.3 on 2023-07-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tormoz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dvigatel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electron',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podveska',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vihlop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
